image: 
  name: immcantation/test:devel

pipelines:
  default:
    - step:
        script:
          - sed -i '/test/ d' .Rbuildignore
          - Rscript -e "install.packages('BiocManager')"
          - Rscript -e "BiocManager::install('ggtree')"
          - Rscript -e 'remotes::install_version("phangorn", "2.11.1", upgrade="never")'
          - Rscript tests/setup/install_dep.R
          - R CMD build .
          - R CMD check *.tar.gz --as-cran --run-donttest --timings
