image: 
  name: immcantation/test:devel

pipelines:
  default:
    - step:
        script:
          - sed -i '/test/ d' .Rbuildignore
          - R CMD build .
          - R CMD check *.tar.gz --as-cran --run-donttest --timings
