site_name: dowser
site_favicon: img/immcantation.ico
repo_url: https://bitbucket.org/kleinstein/dowser
theme: readthedocs
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - toc:
      permalink: True
docs_dir: 'docs'
pages:
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Package Overview': topics/dowser.md
    - 'Release Notes': news.md
  - 'Vignettes':
    - 'Quickstart': vignettes/Quickstart-Vignette.md
    - 'Build lineage trees': vignettes/Building-Trees-Vignette.md
    - 'Plot lineage trees': vignettes/Plotting-Trees-Vignette.md
  - 'Help Topics':
    - 'Define clones and ubclones':
      - topics/getSubclones.md
      - topics/formatClones.md
      - topics/createGermlines.md
      - topics/makeAirrClone.md
      - topics/airrClone-class.md
    - 'Build trees':
      - topics/getTrees.md
      - topics/bootstrapTrees.md
      - topics/buildIgphyml.md
      - topics/buildPML.md
      - topics/buildPhylo.md
      - topics/buildPratchet.md
    - 'Visualize trees':
      - topics/plotTrees.md
      - topics/treesToPDF.md
      - topics/colorTrees.md
      - topics/getPalette.md
      - topics/collapseNodes.md
      - topics/scaleBranches.md
      - topics/rerootTree.md
    - 'Reconstruct intermediate sequences':
      - topics/getSeq.md
    - 'Discrete trait analysis':
      - topics/makeModelFile.md
      - topics/readModelFile.md
      - topics/testPS.md
      - topics/testSC.md
      - topics/testSP.md