theme: readthedocs
site_name: dowser
site_url: https://dowser.readthedocs.io
repo_url: https://github.com/immcantation/dowser
edit_uri: src/master/docs/
theme:
  name: readthedocs
  navigation_depth: 2
  collapse_navigation: False
  sticky_navigation: False
  locale: en
  titles_only: False
  #logo: img/rod_white_leaf_light_background.png
  analytics:
    gtag: G-CD0939NYSC
markdown_extensions:
  - admonition
  - def_list
  - sane_lists
  - smarty
  - pymdownx.arithmatex
  - toc:
      permalink: True
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - path: js/custom.js
    defer: true  
nav:
  - 'About':
    - 'Introduction': index.md
    - 'Contributing': contributing.md
    - 'Package Overview': topics/dowser.md
    - 'Release Notes': news.md
  - 'Vignettes':
    - 'Quickstart': vignettes/Quickstart-Vignette.md
    - 'Reconstruct Clonal Germlines': vignettes/Germlines-Vignette.md
    - 'Build Lineage Trees': vignettes/Building-Trees-Vignette.md
    - 'Paired Heavy and Light Chain Trees': vignettes/Resolve-Light-Chains-Vignette.md
    - 'Plot Lineage Trees': vignettes/Plotting-Trees-Vignette.md
    - 'Reconstruct Intermediate Sequences': vignettes/Sequences-Vignette.md
    - 'Migration, Differentiation, Class-switching Analysis': vignettes/Discrete-Trait-Vignette.md
    - 'Time-based Longitudinal Analysis': vignettes/Measurable-Evolution.md
  - 'Help Topics':
    - topics/airrClone-class.md
    - topics/BiopsyTrees.md
    - topics/bootstrapTrees.md
    - topics/buildClonalGermline.md
    - topics/buildGermline.md
    - topics/buildIgphyml.md
    - topics/buildPhylo.md
    - topics/buildPML.md
    - topics/buildPratchet.md
    - topics/buildRAxML.md
    - topics/calcRF.md
    - topics/collapseNodes.md
    - topics/colorTrees.md
    - topics/condenseTrees.md
    - topics/correlationTest.md
    - topics/createAllGermlines.md
    - topics/createGermlines.md
    - topics/downsampleClone.md
    - topics/dowser-package.md
    - topics/ExampleAirr.md
    - topics/ExampleClones.md
    - topics/ExampleDbChangeo.md
    - topics/ExampleMixedClones.md
    - topics/ExampleMixedDb.md
    - topics/exportTrees.md
    - topics/findSwitches.md
    - topics/formatClones.md
    - topics/getBootstraps.md
    - topics/getDivergence.md
    - topics/getGermline.md
    - topics/getNodeSeq.md
    - topics/getPalette.md
    - topics/getSeq.md
    - topics/getSubclones.md
    - topics/getSubTaxa.md
    - topics/getTrees.md
    - topics/getTreesAndUCAs.md
    - topics/IsotypeTrees.md
    - topics/makeAirrClone.md
    - topics/makeModelFile.md
    - topics/maskCodons.md
    - topics/maskSequences.md
    - topics/plotTrees.md
    - topics/readFasta.md
    - topics/readIMGT.md
    - topics/readLineages.md
    - topics/readModelFile.md
    - topics/reconIgPhyML.md
    - topics/rerootTree.md
    - topics/resolveLightChains.md
    - topics/resolvePolytomies.md
    - topics/runCorrelationTest.md
    - topics/scaleBranches.md
    - topics/rerootTree.md
    #- 'Intermediate sequence functions':
    - topics/getAllSeqs.md
    - topics/getNodeSeq.md
    - topics/dfToFasta.md
    - topics/getSubTaxa.md
    #- 'Discrete trait analysis functions':
    - topics/findSwitches.md
    - topics/testPS.md
    - topics/testSC.md
    - topics/testSP.md
    - topics/TimeTrees.md
    - topics/treesToPDF.md
    - topics/writeCloneSequences.md
    - topics/writeLineageFile.md
