theme: readthedocs
site_name: dowser
docs_dir: docs
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - pymdownx.arithmatex
  - toc:
      permalink: True
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
pages:
  - 'About':
    - 'Introduction': index.md
    - 'Package Overview': topics/dowser.md
    - 'Release Notes': news.md
  - 'Vignettes':
    - 'Build Lineage Trees': vignettes/Building-Trees-Vignette.md
    - 'Discrete Trait Analysis': vignettes/Discrete-Trait-Vignette.md
    - 'Reconstruct Clonal Germlines': vignettes/Germlines-Vignette.md
    - 'Measurable evolution': vignettes/Measurable-Evolution.md
    - 'Plotting Lineage Trees': vignettes/Plotting-Trees-Vignette.md
    - 'Quickstart': vignettes/Quickstart-Vignette.md
    - 'Building trees with paired heavy and light chain data': vignettes/Resolve-Light-Chains-Vignette.md
    - 'Reconstruct Intermediate Sequences': vignettes/Sequences-Vignette.md
  - 'Help Topics':
    - topics/airrClone-class.md
    - topics/BiopsyTrees.md
    - topics/bootstrapTrees.md
    - topics/buildClonalGermline.md
    - topics/buildGermline.md
    - topics/buildIgphyml.md
    - topics/buildPhylo.md
    - topics/buildPML.md
    - topics/buildPratchet.md
    - topics/buildRAxML.md
    - topics/calcRF.md
    - topics/checkDivergence.md
    - topics/collapseNodes.md
    - topics/colorTrees.md
    - topics/condenseTrees.md
    - topics/correlationTest.md
    - topics/createGermlines.md
    - topics/dfToFasta.md
    - topics/downsampleClone.md
    - topics/dowser-package.md
    - topics/ExampleAirr.md
    - topics/ExampleClones.md
    - topics/ExampleDbChangeo.md
    - topics/ExampleMixedClones.md
    - topics/ExampleMixedDb.md
    - topics/exportTrees.md
    - topics/findSwitches.md
    - topics/formatClones.md
    - topics/getAllSeqs.md
    - topics/getBootstraps.md
    - topics/getDivergence.md
    - topics/getGermline.md
    - topics/getNodeSeq.md
    - topics/getPalette.md
    - topics/getSeq.md
    - topics/getSubclones.md
    - topics/getSubTaxa.md
    - topics/getTrees.md
    - topics/IsotypeTrees.md
    - topics/makeAirrClone.md
    - topics/makeModelFile.md
    - topics/maskCodons.md
    - topics/maskSequences.md
    - topics/plotTrees.md
    - topics/readFasta.md
    - topics/readIMGT.md
    - topics/readLineages.md
    - topics/readModelFile.md
    - topics/reconIgPhyML.md
    - topics/rerootTree.md
    - topics/resolveLightChains.md
    - topics/resolvePolytomies.md
    - topics/runCorrelationTest.md
    - topics/sampleClone.md
    - topics/sampleClones.md
    - topics/scaleBranches.md
    - topics/stitchRegions.md
    - topics/stitchVDJ.md
    - topics/stopCodonCheck.md
    - topics/testPS.md
    - topics/testSC.md
    - topics/testSP.md
    - topics/TimeTrees.md
    - topics/treesToPDF.md
    - topics/writeCloneSequences.md
    - topics/writeLineageFile.md
