site_name: dowser
site_url: https://dowser.readthedocs.io
site_favicon: img/favicon.ico
repo_url: https://bitbucket.org/kleinstein/dowser
edit_uri: src/master/docs/
theme:
  name: readthedocs
  navigation_depth: 2
  collapse_navigation: False
  titles_only: False
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - toc:
      baselevel: 1
      toc_depth: 1-4
      permalink: True
docs_dir: 'docs'
nav:
  - 'Immcantation Portal': https://immcantation.readthedocs.io/
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Package Overview': topics/dowser.md
    - 'Release Notes': news.md
  - 'Vignettes':
    - 'Quickstart': vignettes/Quickstart-Vignette.md
    - 'Construct clonal germlines': vignettes/Germlines-Vignette.md
    - 'Build lineage trees': vignettes/Building-Trees-Vignette.md
    - 'Plot lineage trees': vignettes/Plotting-Trees-Vignette.md
    - 'Construct intermediate sequences': vignettes/Sequences-Vignette.md
  - 'Help Topics':
    - 'Germline construction functions':
      - topics/readIMGT.md
      - topics/createGermlines.md
    - 'Clone formating functions':
      - topics/formatClones.md
      - topics/getSubclones.md
      - topics/makeAirrClone.md
      - topics/airrClone-class.md
    - 'Tree building functions':
      - topics/getTrees.md
      - topics/bootstrapTrees.md
      - topics/buildIgphyml.md
      - topics/buildPML.md
      - topics/buildPhylo.md
      - topics/buildPratchet.md
    - 'Visualization functions':
      - topics/plotTrees.md
      - topics/treesToPDF.md
      - topics/colorTrees.md
      - topics/getPalette.md
      - topics/collapseNodes.md
      - topics/scaleBranches.md
      - topics/rerootTree.md
    - 'Intermediate sequence functions':
      - topics/getSeq.md
    - 'Discrete trait analysis functions':
      - topics/makeModelFile.md
      - topics/readModelFile.md
      - topics/testPS.md
      - topics/testSC.md
      - topics/testSP.md