#library(testthat)
#library(dowser)

test_that("makeAirrClone",{
  # Example AIRR data.frame
  db <- data.frame(sequence_id=LETTERS[1:4],
                   sequence_alignment=c("CCCCTGGG", "CCCCTGGN", "NAACTGGN", "NNNCTGNN"),
                   v_call="Homsap IGKV1-39*01 F",
                   j_call="Homsap IGKJ5*01 F",
                   junction_length=2,
                   germline_alignment="CCCCAGGG",
                   clone_id=1,
                   isotype=c("IgG", "IgG", "IgM", "IgA"),
                   stringsAsFactors=FALSE)
  db_l <- data.frame(sequence_id=LETTERS[1:4],
                     sequence_alignment=c("CCCCTGGG", "CCCCTGGN", "NAACTGGN", "NNNCTGNN"),
                     v_call="Homsap IGKV1-39*01 F",
                     j_call="Homsap IGKJ5*01 F",
                     junction_length=2,
                     germline_alignment="CCCCAGGG",
                     clone_id=1,
                     isotype=c("IgG", "IgG", "IgM", "IgA"),
                     cell_id =1,
                     locus=c("IGK", "IGK", "IGK", "IGK"),
                     stringsAsFactors=FALSE)

  exp <- data.frame("sequence_id"=c("C", "A"),
                    "sequence"=c("NAACTGGNN", "CCCCTGGGN"),
                    "lsequence"=c("", ""),
                    "hlsequence"=c("NAACTGGNN", "CCCCTGGGN"),
                    "collapse_count"=c(1, 2),
                    stringsAsFactors=FALSE)

  exp_trait <- data.frame("sequence_id"=c("D", "A", "C"),
                          "sequence"=c("NNNCTGNNN","CCCCTGGGN", "NAACTGGNN"),
                          "isotype"=c("IgA","IgG","IgM"),
                          "lsequence"=c("", "", ""),
                          "hlsequence"=c("NNNCTGNNN","CCCCTGGGN", "NAACTGGNN"),
                          "collapse_count"=c(1, 2, 1),
                          stringsAsFactors=FALSE)

  exp_l <- data.frame("sequence_id"=c("C", "A"),
                      "sequence"=c("NAACTGGNN", "CCCCTGGGN"),
                      "junction_length"=2,
                      "cell_id"=1,
                      "lsequence"=c("NAACTGGNN", "CCCCTGGGN"),
                      "hlsequence"=c("NAACTGGNN", "CCCCTGGGN"),
                      "locus" = "IGK",
                      "collapse_count"=c(1, 2),
                      stringsAsFactors=FALSE)

  # Without splitting by trait value
  clones <- formatClones(db,germ="germline_alignment",randomize=FALSE,
                         use_regions=FALSE)
  clone <- clones$data[[1]]

  expect_equal(clone@clone, "1")
  expect_equal(clone@germline, "CCCCAGGGN")
  expect_equal(clone@v_gene, "IGKV1-39")
  expect_equal(clone@j_gene, "IGKJ5")
  expect_equal(clone@junc_len, 2)
  expect_equal(clone@locus,rep("N",length=9))
  expect_equal(clone@phylo_seq,"sequence")
  expect_equal(clone@lgermline,"")
  expect_equal(clone@hlgermline,"CCCCAGGGN")
  expect_equal(clone@germline,"CCCCAGGGN")
  expect_equal(clone@data, exp, tolerance=0.001)

  # With splitting by trait value
  clones <- formatClones(db,germ="germline_alignment",randomize=FALSE,
                         trait="isotype",add_count=TRUE,use_regions=FALSE)
  clone <- clones$data[[1]]

  expect_equal(clone@clone, "1")
  expect_equal(clone@germline, "CCCCAGGGN")
  expect_equal(clone@v_gene, "IGKV1-39")
  expect_equal(clone@j_gene, "IGKJ5")
  expect_equal(clone@junc_len, 2)
  expect_equal(clone@locus,rep("N",length=9))
  expect_equal(clone@phylo_seq,"sequence")
  expect_equal(clone@lgermline,"")
  expect_equal(clone@hlgermline,"CCCCAGGGN")
  expect_equal(clone@germline,"CCCCAGGGN")
  expect_equal(clone@data, exp_trait, tolerance=0.001)

  clones <- formatClones(db_l,germ="germline_alignment",randomize=FALSE,
                         use_regions=FALSE, chain="L", seq = "sequence_alignment")
  clone <- clones$data[[1]]

  expect_equal(clone@clone, "1")
  expect_equal(clone@germline, "")
  expect_equal(clone@lgermline, "CCCCAGGGN")
  expect_equal(clone@hlgermline, "CCCCAGGGN")
  expect_equal(clone@hlgermline, clone@lgermline)
  expect_equal(clone@v_gene, "IGKV1-39")
  expect_equal(clone@j_gene, "IGKJ5")
  expect_equal(clone@junc_len, 2)
  expect_equal(clone@locus,rep("IGK",length=9))
  expect_equal(clone@region,rep("N",length=9))
  expect_equal(clone@phylo_seq,"lsequence")
  expect_equal(clone@data, exp_l, tolerance=0.001)
})

test_that("getTreesPhangorn", {
  # Preprocess clone
  db <- data.frame(sequence_id=LETTERS[1:4],
                   sequence_alignment=c("CCCCTGGG", "CCCCTGGN", "NAACTGGN", "NNNCTGNN"),
                   v_call="Homsap IGKV1-39*01 F",
                   j_call="Homsap IGKJ5*01 F",
                   junction_length=2,
                   germline_alignment="CCCCAGGG",
                   clone_id=1,
                   isotype=c("IgG", "IgG", "IgM", "IgA"),
                   stringsAsFactors=FALSE)

  clones <- formatClones(db,germ="germline_alignment",
                         randomize=FALSE, use_regions=FALSE)

  # build parsimony tree with phangorn
  trees <- getTrees(clones, resolve_random=FALSE)
  trees <- scaleBranches(trees)
  seqs <- unlist(lapply(trees$trees[[1]]$nodes,function(x)x$sequence))

  # note, node re-order 11/17/22
  expect_equal(trees$trees[[1]]$edge.length,
               c(1,0,2,0))
  expect_equal(trees$trees[[1]]$edge[,1],
               c(4,5,5,4))
  expect_equal(trees$trees[[1]]$edge[,2],
               c(5,2,1,3))
  expect_equal(trees$trees[[1]]$tip.label,
               c("C","A","Germline"))
  expect_equal(seqs,c("NAACTGGNN","CCCCTGGGN","CCCCAGGGN",
                      "CCCCAGGGN","CCCCTGGGN"))
})


test_that("getGermlines", {
  # Preprocess clone
  db <- data.frame(sequence_id=LETTERS[1:5],
                   sequence_alignment=c(
                     "CAGGTGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCTT",
                     "AAGATGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTC",
                     "CCGGTGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCAAAACGTCTTTATGGCCAGGGGACAATGGTCAGGGTCTCTT",
                     "CTGGTGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCAAAACGTCTTTATGGCCAGGGGACAATGGTCAGGGTCTCTT",
                     "CGGGTGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCAAAACGTCTTTATGGCCAGGGGACAATGGTCAGGGTCTCTT"),
                   v_call="IGHV0-0*02",
                   d_call="IGHD0-0*01,IGHD0-1*01,IGHD0/OR15-0a*01",
                   j_call=c(rep("IGHJ0*01,IGHJ0*02",2),rep("IGHJ1*00",3)),
                   np1_length=15,
                   np2_length=7,
                   v_germline_start=1,
                   v_germline_end=320,
                   d_germline_start=11,
                   d_germline_end=16,
                   j_germline_start=20,
                   j_germline_end=47,
                   junction_length=41,
                   clone_id=c(1,1,1,1,1),
                   subject_id=c(1,1,2,2,2),
                   locus="IGH",
                   stringsAsFactors=FALSE)


  references <- list()
  references <- list()
  references$IGH <- list()
  references$IGH$V <- list()
  references$IGH$D <- list()
  references$IGH$J <- list()
  references$IGH$V[["IGHV0-0*02"]] <- "CAGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGA"
  references$IGH$D[["IGHD0-0*01"]] <- "GTATTACGATTTTTGGAGTGGTTATTATACC"
  references$IGH$J[["IGHJ0*01"]] <- "TGATGCTTTTGATGTCTGGGGCCAAGGGACAATGGTCACCGTCTCTTCAG"
  references$IGH$J[["IGHJ1*00"]] <- "TGATGCAAAACATGTCTGGGGCCAAGGGACAATGGTCAGGGTCTCTTCAG"
  # reconstruct germline
  dbg <- createGermlines(db,references,fields="subject_id")
  exp <- db

  exp$sequence_alignment=c(
    "CAGGTGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCTT",
    "AAGATGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCNN",
    "CCGGTGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCAAAACGTCTTTATGGCCAGGGGACAATGGTCAGGGTCTCTT",
    "CTGGTGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCAAAACGTCTTTATGGCCAGGGGACAATGGTCAGGGTCTCTT",
    "CGGGTGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCAAAACGTCTTTATGGCCAGGGGACAATGGTCAGGGTCTCTT")


  exp$v_germline_length <- 320
  exp$d_germline_length <- 6
  exp$j_germline_length <- 28
  exp$germline_alignment <- c(
    "CAGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNTTTTGGNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTT",
    "CAGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNTTTTGGNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTT",
    "CCGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNTTTTCGNNNNNNNGGCCAAGGGACAATGGTCAGGGTCTCTT",
    "CTGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNTTTTCGNNNNNNNGGCCAAGGGACAATGGTCAGGGTCTCTT",
    "CGGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNTTTTCGNNNNNNNGGCCAAGGGACAATGGTCAGGGTCTCTT"
  )
  exp$germline_alignment_d_mask <- c(
    "CAGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTT",
    "CAGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTT",
    "CCGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCAGGGTCTCTT",
    "CTGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCAGGGTCTCTT",
    "CGGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCAGGGTCTCTT")

  #  Temporary 'fix' (basically ignore the test that is WIP)
  dbg <- dbg[1:2,]
  exp <- exp[1:2,]

  expect_equal(dbg, exp)
  # build parsimony tree with phangorn
  clones <- formatClones(dbg,randomize=FALSE)
  trees <- getTrees(clones, resolve_random=FALSE)
  trees <- scaleBranches(trees)

  seqs <- unlist(lapply(trees$trees[[1]]$nodes,function(x)x$sequence))
  # note, node re-order 11/17/22
  expect_equal(trees$trees[[1]]$edge.length,
               c(27,2,0,0))
  expect_equal(trees$trees[[1]]$edge[,1],
               c(4,5,5,4))
  expect_equal(trees$trees[[1]]$edge[,2],
               c(5,2,1,3))
  expect_equal(trees$trees[[1]]$tip.label,
               c("A","B","Germline"))
  expect_equal(seqs,c(
    "CAGGTGCAGCTGGTGGAGTCTGGCGGAGGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTCAGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGATGGAGTTGATATATTCTTTGCAAATTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCTTNN",
    "AAGATGCAGCTGGTGGAGTCTGGCGGAGGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTCAGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGATGGAGTTGATATATTCTTTGCAAATTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCNNNN",
    "CAGGTGCAGCTGGTGGAGTCTGGGGGAGGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTCAGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGATGGAAGTAATAAATACTATGCAGACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTTNN",
    "CAGGTGCAGCTGGTGGAGTCTGGGGGAGGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTCAGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGATGGAAGTAATAAATACTATGCAGACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTTNN",
    "CAGGTGCAGCTGGTGGAGTCTGGCGGAGGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTCAGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGATGGAGTTGATATATTCTTTGCAAATTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCTTNN"
  ))
  expect_equal(alakazam::seqDist(seqs[[4]],seqs[[5]]),27)
  expect_equal(alakazam::seqDist(seqs[[1]],seqs[[5]]),0)
  expect_equal(alakazam::seqDist(seqs[[2]],seqs[[5]]),2)
  expect_equal(alakazam::seqDist(seqs[[3]],seqs[[5]]),27)
})

# Test changeo compatability
test_that("changeo", {
  # Preprocess clone
  db <- data.frame(SEQUENCE_ID=LETTERS[1:2],
                   SEQUENCE_IMGT=c(
                     "CAGGTGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCTT",
                     "AAGATGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTC"),
                   V_CALL="IGHV0-0*02",
                   D_CALL="IGHD0-0*01,IGHD0-1*01,IGHD0/OR15-0a*01",
                   J_CALL="IGHJ0*01,IGHJ0*02",
                   NP1_LENGTH=15,
                   NP2_LENGTH=7,
                   V_GERM_START_IMGT=1,
                   V_GERM_END_IMGT=320,
                   D_GERM_START=11,
                   D_GERM_END=16,
                   J_GERM_START=20,
                   J_GERM_END=47,
                   JUNCTION_LENGTH=41,
                   CLONE=1,
                   LOCUS="IGH",
                   stringsAsFactors=FALSE)

  references <- list()
  references <- list()
  references$IGH <- list()
  references$IGH$V <- list()
  references$IGH$D <- list()
  references$IGH$J <- list()
  references$IGH$V[["IGHV0-0*02"]] <- "CAGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGA"
  references$IGH$D[["IGHD0-0*01"]] <- "GTATTACGATTTTTGGAGTGGTTATTATACC"
  references$IGH$J[["IGHJ0*01"]] <- "TGATGCTTTTGATGTCTGGGGCCAAGGGACAATGGTCACCGTCTCTTCAG"

  # reconstruct germline
  dbg <- createGermlines(db,references,
                         seq="SEQUENCE_IMGT", clone="CLONE", id="SEQUENCE_ID",
                         np1_length="NP1_LENGTH", np2_length="NP2_LENGTH",
                         v_call="V_CALL", d_call="D_CALL", j_call="J_CALL",
                         v_germ_start="V_GERM_START_IMGT",v_germ_end="V_GERM_END_IMGT",
                         d_germ_start="D_GERM_START",d_germ_end="D_GERM_END",
                         j_germ_start="J_GERM_START",j_germ_end="J_GERM_END",locus="LOCUS")

  exp <- db
  exp$SEQUENCE_IMGT=c(
    "CAGGTGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCTT",
    "AAGATGCAGCTGGTGGAGTCTGGCGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTC............AGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGAT......GGAGTTGATATATTCTTTGCAAATTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCNN")
  exp$v_germline_length <- 320
  exp$d_germline_length <- 6
  exp$j_germline_length <- 28
  exp$germline_alignment <- c(
    "CAGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNTTTTGGNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTT",
    "CAGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNTTTTGGNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTT")
  exp$germline_alignment_d_mask <- c(
    "CAGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTT",
    "CAGGTGCAGCTGGTGGAGTCTGGGGGA...GGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTC............AGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGAT......GGAAGTAATAAATACTATGCAGACTCCGTGAAG...GGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTT")

  expect_equal(dbg, exp)

  # build parsimony tree with phangorn
  clones <- formatClones(dbg,randomize=FALSE,
                         id="SEQUENCE_ID", clone="CLONE", seq="SEQUENCE_IMGT",
                         v_call="V_CALL", j_call="J_CALL",
                         junc_len="JUNCTION_LENGTH")
  trees <- getTrees(clones, resolve_random=FALSE)
  trees <- scaleBranches(trees)

  seqs <- unlist(lapply(trees$trees[[1]]$nodes,function(x)x$sequence))

  # note, node re-order 11/17/22
  expect_equal(trees$trees[[1]]$edge.length,
               c(27,2,0,0))
  expect_equal(trees$trees[[1]]$edge[,1],
               c(4,5,5,4))
  expect_equal(trees$trees[[1]]$edge[,2],
               c(5,2,1,3))
  expect_equal(trees$trees[[1]]$tip.label,
               c("A","B","Germline"))
  expect_equal(seqs,c(
    "CAGGTGCAGCTGGTGGAGTCTGGCGGAGGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTCAGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGATGGAGTTGATATATTCTTTGCAAATTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCTTNN",
    "AAGATGCAGCTGGTGGAGTCTGGCGGAGGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTCAGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGATGGAGTTGATATATTCTTTGCAAATTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCNNNN",
    "CAGGTGCAGCTGGTGGAGTCTGGGGGAGGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTCAGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGATGGAAGTAATAAATACTATGCAGACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTTNN",
    "CAGGTGCAGCTGGTGGAGTCTGGGGGAGGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCTGGATTCACCTTCAGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCATTTATACGGTATGATGGAAGTAATAAATACTATGCAGACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGANNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCCAAGGGACAATGGTCACCGTCTCTTNN",
    "CAGGTGCAGCTGGTGGAGTCTGGCGGAGGCGTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCGGCGTCTGGATTCACCTTCAGTCATTATGACATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGTCATTTATTCGGCGTGATGGAGTTGATATATTCTTTGCAAATTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACCCTATTTCTGCAAATGAACAGCCTAAGAACTGCGGACACGGCTCTCTATTACTGTGCGAAAGATGTGGGGTCTTGGGCTTTTGGTCTTTATGGCCAGGGGACAATGGTCACCGTCTCTTNN"
  ))
  expect_equal(alakazam::seqDist(seqs[[4]],seqs[[5]]),27)
  expect_equal(alakazam::seqDist(seqs[[1]],seqs[[5]]),0)
  expect_equal(alakazam::seqDist(seqs[[2]],seqs[[5]]),2)
  expect_equal(alakazam::seqDist(seqs[[3]],seqs[[5]]),27)
})
